# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

#target pods

def public_pods
    
    pod 'Masonry','~> 1.0.2'
    pod 'AFNetworking', '~> 3.1.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
    pod 'JSONModel'
    pod 'HLBagel', '~>  1.3.5'
    pod 'SDWebImage', '~> 5.6.1'
    pod 'MBProgressHUD', '~> 1.2.0'
end


target 'MiniProgramsOfReactNative' do
    
    public_pods

end









